main_cam_pitch_controller:
    joint: $(arg prefix)main_cam_pitch_joint
    pid:
        p: 100.0
        i: 0.0
        d: 5.0
    type: effort_controllers/JointPositionController

main_cam_yaw_controller:
    joint: $(arg prefix)main_cam_yaw_joint
    pid:
        p: 100.0
        i: 0.0
        d: 5.0
    type: effort_controllers/JointPositionController
