base_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: '$(arg prefix)l_wheel_joint'
  right_wheel: '$(arg prefix)r_wheel_joint'
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  publish_rate: 50

  # odom -> base_link
  odom_frame_id: $(arg prefix)odom
  base_frame_id: $(arg prefix)base_link

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.37476
  wheel_radius : 0.0602

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 10

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.5  # m/s
      has_acceleration_limits: true
      max_acceleration       : 5  # m/s^2
      # has_jerk_limits        : true
      # max_jerk               : 4.0  # m/s^3
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 10  # rad/s^2
      # has_jerk_limits        : true
      # max_jerk               : 2.5  # rad/s^3

# To avoid error
gazebo_ros_control:
  pid_gains:
    $(arg prefix)l_wheel_joint: {p: 3000.0, i: 0.0, d: 2.0} 
    $(arg prefix)r_wheel_joint: {p: 3000.0, i: 0.0, d: 2.0} 