// Generated by gencpp from file unity_gopher/PositionService.msg
// DO NOT EDIT!


#ifndef UNITY_GOPHER_MESSAGE_POSITIONSERVICE_H
#define UNITY_GOPHER_MESSAGE_POSITIONSERVICE_H

#include <ros/service_traits.h>


#include <unity_gopher/PositionServiceRequest.h>
#include <unity_gopher/PositionServiceResponse.h>


namespace unity_gopher
{

struct PositionService
{

typedef PositionServiceRequest Request;
typedef PositionServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PositionService
} // namespace unity_gopher


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::unity_gopher::PositionService > {
  static const char* value()
  {
    return "5190f887b70decc2fafe0ae2939b233a";
  }

  static const char* value(const ::unity_gopher::PositionService&) { return value(); }
};

template<>
struct DataType< ::unity_gopher::PositionService > {
  static const char* value()
  {
    return "unity_gopher/PositionService";
  }

  static const char* value(const ::unity_gopher::PositionService&) { return value(); }
};


// service_traits::MD5Sum< ::unity_gopher::PositionServiceRequest> should match
// service_traits::MD5Sum< ::unity_gopher::PositionService >
template<>
struct MD5Sum< ::unity_gopher::PositionServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::unity_gopher::PositionService >::value();
  }
  static const char* value(const ::unity_gopher::PositionServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::unity_gopher::PositionServiceRequest> should match
// service_traits::DataType< ::unity_gopher::PositionService >
template<>
struct DataType< ::unity_gopher::PositionServiceRequest>
{
  static const char* value()
  {
    return DataType< ::unity_gopher::PositionService >::value();
  }
  static const char* value(const ::unity_gopher::PositionServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::unity_gopher::PositionServiceResponse> should match
// service_traits::MD5Sum< ::unity_gopher::PositionService >
template<>
struct MD5Sum< ::unity_gopher::PositionServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::unity_gopher::PositionService >::value();
  }
  static const char* value(const ::unity_gopher::PositionServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::unity_gopher::PositionServiceResponse> should match
// service_traits::DataType< ::unity_gopher::PositionService >
template<>
struct DataType< ::unity_gopher::PositionServiceResponse>
{
  static const char* value()
  {
    return DataType< ::unity_gopher::PositionService >::value();
  }
  static const char* value(const ::unity_gopher::PositionServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNITY_GOPHER_MESSAGE_POSITIONSERVICE_H
