controller_list:
  - name: fake_left_arm_controller
    type: $(arg execution_type)
    joints:
      - gopher/left_arm_joint_1
      - gopher/left_arm_joint_2
      - gopher/left_arm_joint_3
      - gopher/left_arm_joint_4
      - gopher/left_arm_joint_5
      - gopher/left_arm_joint_6
      - gopher/left_arm_joint_7
  - name: fake_right_arm_controller
    type: $(arg execution_type)
    joints:
      - gopher/right_arm_joint_1
      - gopher/right_arm_joint_2
      - gopher/right_arm_joint_3
      - gopher/right_arm_joint_4
      - gopher/right_arm_joint_5
      - gopher/right_arm_joint_6
      - gopher/right_arm_joint_7
initial:  # Define initial robot poses.
  - group: left_arm
    pose: home_left
  - group: right_arm
    pose: home_right