# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_arm
  joint_model_group_pose: home_left
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - gopher/l_wheel_joint
    - gopher/r_wheel_joint
    - gopher/left_arm_joint_1
    - gopher/left_arm_joint_2
    - gopher/left_arm_joint_3
    - gopher/left_arm_joint_4
    - gopher/left_arm_joint_5
    - gopher/left_arm_joint_6
    - gopher/left_arm_joint_7
    - gopher/left_arm_finger_joint
    - gopher/main_cam_yaw_joint
    - gopher/main_cam_pitch_joint
    - gopher/right_arm_joint_1
    - gopher/right_arm_joint_2
    - gopher/right_arm_joint_3
    - gopher/right_arm_joint_4
    - gopher/right_arm_joint_5
    - gopher/right_arm_joint_6
    - gopher/right_arm_joint_7
    - gopher/right_arm_finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - gopher/left_arm_joint_1
      - gopher/left_arm_joint_2
      - gopher/left_arm_joint_3
      - gopher/left_arm_joint_4
      - gopher/left_arm_joint_5
      - gopher/left_arm_joint_6
      - gopher/left_arm_joint_7
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - gopher/right_arm_joint_1
      - gopher/right_arm_joint_2
      - gopher/right_arm_joint_3
      - gopher/right_arm_joint_4
      - gopher/right_arm_joint_5
      - gopher/right_arm_joint_6
      - gopher/right_arm_joint_7